
<!-- Criação da tabela RaceHistory -->

CREATE TABLE IF NOT EXISTS public."RaceHistory"
(
    "IdRaceHistory" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "IdCompetitor" integer NOT NULL,
    "IdRaceTrack" integer NOT NULL,
    "RaceDate" timestamp without time zone NOT NULL,
    "TimeSpent" double precision NOT NULL,
    CONSTRAINT "PK_RaceHistory" PRIMARY KEY ("IdRaceHistory")
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public."RaceHistory"
    OWNER to postgres;