
<!-- Criação da tabela RaceTrack -->

CREATE TABLE IF NOT EXISTS public."RaceTrack"
(
    "IdRaceTrack" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "Description" character varying(50) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT "PK_RaceTrack" PRIMARY KEY ("IdRaceTrack")
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public."RaceTrack"
    OWNER to postgres;